/**
 * EDC Design Token System Template
 *
 * Extracted from: /Users/kcdacre8tor/edc-web/lib/theme/app_theme_extensions.dart
 *
 * Comprehensive design token system including:
 * - AppSpacing: 8-point spacing scale with semantic patterns
 * - AppColors: Semantic color tokens for glass/dark backgrounds
 * - AppRadius: Border radius tokens with pre-built patterns
 * - AppBorders: Glass and accent border styles
 * - AppAnimations: Duration constants and staggered delays
 * - AppSizes: Icon, avatar, card, and button sizes
 * - AppBlur: Glassmorphic blur strength levels
 */

import type { Template } from "../../../core/types.js";

// ============================================================================
// HANDLEBARS TEMPLATE SOURCE
// ============================================================================

export const DESIGN_TOKENS_SOURCE = `// GENERATED CODE - DO NOT MODIFY BY HAND
// EDC Design Token System
// Generated by offline-flutter-pwa-builder

import 'package:flutter/material.dart';

// ============================================================================
// THEME EXTENSION - Use with Theme.of(context).extension<AppThemeExtension>()
// ============================================================================

@immutable
class AppThemeExtension extends ThemeExtension<AppThemeExtension> {
  const AppThemeExtension({
    required this.appSpacing,
    required this.appColors,
    required this.appRadius,
    required this.appBorders,
    required this.appAnimations,
    required this.appSizes,
    required this.appBlur,
  });

  final AppSpacing appSpacing;
  final AppColors appColors;
  final AppRadius appRadius;
  final AppBorders appBorders;
  final AppAnimations appAnimations;
  final AppSizes appSizes;
  final AppBlur appBlur;

  @override
  ThemeExtension<AppThemeExtension> copyWith({
    AppSpacing? appSpacing,
    AppColors? appColors,
    AppRadius? appRadius,
    AppBorders? appBorders,
    AppAnimations? appAnimations,
    AppSizes? appSizes,
    AppBlur? appBlur,
  }) {
    return AppThemeExtension(
      appSpacing: appSpacing ?? this.appSpacing,
      appColors: appColors ?? this.appColors,
      appRadius: appRadius ?? this.appRadius,
      appBorders: appBorders ?? this.appBorders,
      appAnimations: appAnimations ?? this.appAnimations,
      appSizes: appSizes ?? this.appSizes,
      appBlur: appBlur ?? this.appBlur,
    );
  }

  @override
  ThemeExtension<AppThemeExtension> lerp(
    ThemeExtension<AppThemeExtension>? other,
    double t,
  ) {
    if (other is! AppThemeExtension) {
      return this;
    }
    return this; // Tokens don't need interpolation
  }

  /// Default instance with standard values
  static const AppThemeExtension defaults = AppThemeExtension(
    appSpacing: AppSpacing(),
    appColors: AppColors(),
    appRadius: AppRadius(),
    appBorders: AppBorders(),
    appAnimations: AppAnimations(),
    appSizes: AppSizes(),
    appBlur: AppBlur(),
  );
}

// ============================================================================
// SPACING TOKENS - 4px base unit, 8-point scale
// ============================================================================

/// Spacing constants for consistent padding, margin, and gaps
/// Based on 4px base unit with semantic pattern helpers
class AppSpacing {
  const AppSpacing();

  // Base spacing scale (4px base unit)
  static const double xs = {{spacing.xs}};
  static const double sm = {{spacing.sm}};
  static const double md = {{spacing.md}};
  static const double lg = {{spacing.lg}};
  static const double xl = {{spacing.xl}};
  static const double xxl = {{spacing.xxl}};
  static const double xxxl = {{spacing.xxxl}};
  static const double huge = {{spacing.huge}};

  // Common padding patterns
  static const EdgeInsets screenPadding = EdgeInsets.all(xl);
  static const EdgeInsets screenPaddingLarge = EdgeInsets.all(xxl);
  static const EdgeInsets cardPadding = EdgeInsets.all(lg);
  static const EdgeInsets cardPaddingLarge = EdgeInsets.all(xl);
  static const EdgeInsets buttonPadding = EdgeInsets.symmetric(horizontal: xxl, vertical: lg);
  static const EdgeInsets inputPadding = EdgeInsets.symmetric(horizontal: xl, vertical: lg);

  // Horizontal spacing
  static const EdgeInsets horizontalSm = EdgeInsets.symmetric(horizontal: sm);
  static const EdgeInsets horizontalMd = EdgeInsets.symmetric(horizontal: md);
  static const EdgeInsets horizontalLg = EdgeInsets.symmetric(horizontal: lg);
  static const EdgeInsets horizontalXl = EdgeInsets.symmetric(horizontal: xl);
  static const EdgeInsets horizontalXxl = EdgeInsets.symmetric(horizontal: xxl);

  // Vertical spacing
  static const EdgeInsets verticalSm = EdgeInsets.symmetric(vertical: sm);
  static const EdgeInsets verticalMd = EdgeInsets.symmetric(vertical: md);
  static const EdgeInsets verticalLg = EdgeInsets.symmetric(vertical: lg);
  static const EdgeInsets verticalXl = EdgeInsets.symmetric(vertical: xl);
  static const EdgeInsets verticalXxl = EdgeInsets.symmetric(vertical: xxl);

  // Gaps between elements (for Row/Column spacing)
  static const double gapXs = xs;
  static const double gapSm = sm;
  static const double gapMd = md;
  static const double gapLg = lg;
  static const double gapXl = xl;
  static const double gapXxl = xxl;
}

// ============================================================================
// COLOR TOKENS - Semantic colors for glass/gradient backgrounds
// ============================================================================

/// Semantic color tokens for consistent color usage
/// Optimized for glassmorphic and gradient backgrounds
class AppColors {
  const AppColors();

  // Primary theme colors
  static const Color primary = {{flutterColor colors.primary}};
  static const Color accent = {{flutterColor colors.accent}};
  static const Color secondary = {{flutterColor colors.secondary}};
  {{#if colors.gold}}
  static const Color gold = {{flutterColor colors.gold}};
  {{/if}}

  // Text colors on dark/gradient backgrounds
  static const Color primaryText = Colors.white;
  static final Color secondaryText = Colors.white.withValues(alpha: {{colors.textAlpha.secondary}});
  static final Color tertiaryText = Colors.white.withValues(alpha: {{colors.textAlpha.tertiary}});
  static final Color disabledText = Colors.white.withValues(alpha: {{colors.textAlpha.disabled}});

  // Text colors on light backgrounds
  static const Color darkPrimaryText = Colors.black87;
  static final Color darkSecondaryText = Colors.black.withValues(alpha: 0.6);
  static final Color darkTertiaryText = Colors.black.withValues(alpha: 0.4);

  // Accent colors for emphasis
  static final Color accentSubtle = accent.withValues(alpha: 0.6);
  static final Color accentVerySubtle = accent.withValues(alpha: 0.3);

  // Glass overlay colors
  static final Color glassOverlayLight = Colors.white.withValues(alpha: {{colors.glassAlpha.light}});
  static final Color glassOverlayMedium = Colors.white.withValues(alpha: {{colors.glassAlpha.medium}});
  static final Color glassOverlaySubtle = Colors.white.withValues(alpha: {{colors.glassAlpha.subtle}});

  // Border colors
  static final Color primaryBorder = Colors.white.withValues(alpha: {{colors.borderAlpha.primary}});
  static final Color accentBorder = accent.withValues(alpha: {{colors.borderAlpha.accent}});
  static final Color subtleBorder = Colors.white.withValues(alpha: {{colors.borderAlpha.subtle}});

  // Status colors
  static const Color success = {{flutterColor colors.success}};
  static const Color warning = {{flutterColor colors.warning}};
  static const Color error = {{flutterColor colors.error}};
  static const Color info = {{flutterColor colors.info}};
}

// ============================================================================
// RADIUS TOKENS - Border radius with pre-built patterns
// ============================================================================

/// Border radius constants for consistent rounded corners
class AppRadius {
  const AppRadius();

  static const double xs = {{radius.xs}};
  static const double sm = {{radius.sm}};
  static const double md = {{radius.md}};
  static const double lg = {{radius.lg}};
  static const double xl = {{radius.xl}};
  static const double xxl = {{radius.xxl}};
  static const double pill = {{radius.pill}}; // For fully rounded elements

  // Common border radius patterns
  static final BorderRadius smallRadius = BorderRadius.circular(sm);
  static final BorderRadius mediumRadius = BorderRadius.circular(md);
  static final BorderRadius cardRadius = BorderRadius.circular(lg);
  static final BorderRadius largeCardRadius = BorderRadius.circular(xl);
  static final BorderRadius buttonRadius = BorderRadius.circular(xxl);
  static final BorderRadius pillRadius = BorderRadius.circular(pill);
}

// ============================================================================
// BORDER TOKENS - Glass and accent border styles
// ============================================================================

/// Border styles for consistent component borders
class AppBorders {
  const AppBorders();

  // Primary glass borders (accent color)
  static final Border primaryGlass = Border.all(
    color: AppColors.accentBorder,
    width: 2.0,
  );

  static final Border primaryGlassSubtle = Border.all(
    color: AppColors.accent.withValues(alpha: 0.5),
    width: 1.5,
  );

  static final Border primaryGlassThin = Border.all(
    color: AppColors.accent.withValues(alpha: 0.3),
    width: 1.0,
  );

  // Subtle white borders
  static final Border subtle = Border.all(
    color: AppColors.primaryBorder,
    width: 1.0,
  );

  static final Border subtleThick = Border.all(
    color: AppColors.primaryBorder,
    width: 2.0,
  );

  // Icon container borders
  static final Border iconContainer = Border.all(
    color: AppColors.accentBorder,
    width: 1.5,
  );

  // No border
  static const Border none = Border();
}

// ============================================================================
// ANIMATION TOKENS - Duration and timing constants
// ============================================================================

/// Animation duration and timing constants
class AppAnimations {
  const AppAnimations();

  // Standard durations
  static const Duration instant = Duration(milliseconds: {{animations.instant}});
  static const Duration fast = Duration(milliseconds: {{animations.fast}});
  static const Duration normal = Duration(milliseconds: {{animations.normal}});
  static const Duration slow = Duration(milliseconds: {{animations.slow}});
  static const Duration verySlow = Duration(milliseconds: {{animations.verySlow}});

  // Sequential animation delays (for staggered animations)
  static const Duration sequentialShort = Duration(milliseconds: {{animations.sequentialShort}});
  static const Duration sequentialMedium = Duration(milliseconds: {{animations.sequentialMedium}});
  static const Duration sequentialLong = Duration(milliseconds: {{animations.sequentialLong}});

  // Common animation durations by type
  static const Duration fadeIn = slow;
  static const Duration slideIn = normal;
  static const Duration scaleIn = normal;
  static const Duration shimmer = Duration(milliseconds: {{animations.shimmer}});

  // Base delays for screen entry animations
  static const Duration baseDelay = slow;
  static const Duration sectionDelay = Duration(milliseconds: {{animations.sectionDelay}});

  // Press animation (button feedback)
  static const Duration press = Duration(milliseconds: {{animations.press}});
}

// ============================================================================
// SIZE TOKENS - Icon, avatar, card, and button sizes
// ============================================================================

/// Component size constants
class AppSizes {
  const AppSizes();

  // Icon sizes
  static const double iconXs = {{sizes.iconXs}};
  static const double iconSm = {{sizes.iconSm}};
  static const double iconMd = {{sizes.iconMd}};
  static const double iconLg = {{sizes.iconLg}};
  static const double iconXl = {{sizes.iconXl}};

  // Avatar/circle sizes
  static const double avatarSm = {{sizes.avatarSm}};
  static const double avatarMd = {{sizes.avatarMd}};
  static const double avatarLg = {{sizes.avatarLg}};
  static const double avatarXl = {{sizes.avatarXl}};

  // Card sizes
  static const double statCardWidth = {{sizes.statCardWidth}};
  static const double statCardHeight = {{sizes.statCardHeight}};
  static const double quickActionWidth = {{sizes.quickActionWidth}};
  static const double quickActionHeight = {{sizes.quickActionHeight}};

  // App bar
  static const double appBarHeight = {{sizes.appBarHeight}};
  static const double appBarIconSize = iconMd;

  // Button heights
  static const double buttonHeightSm = {{sizes.buttonHeightSm}};
  static const double buttonHeightMd = {{sizes.buttonHeightMd}};
  static const double buttonHeightLg = {{sizes.buttonHeightLg}};
}

// ============================================================================
// BLUR TOKENS - Glassmorphic blur strength levels
// ============================================================================

/// Glass effect blur strength constants
class AppBlur {
  const AppBlur();

  static const double light = {{blur.light}};
  static const double medium = {{blur.medium}};
  static const double strong = {{blur.strong}};
  static const double veryStrong = {{blur.veryStrong}};
}
`;

// ============================================================================
// DEFAULT VALUES FOR HANDLEBARS CONTEXT
// ============================================================================

export interface DesignTokensConfig {
  spacing: {
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    xxl: number;
    xxxl: number;
    huge: number;
  };
  colors: {
    primary: string;
    accent: string;
    secondary: string;
    gold?: string;
    success: string;
    warning: string;
    error: string;
    info: string;
    textAlpha: {
      secondary: number;
      tertiary: number;
      disabled: number;
    };
    glassAlpha: {
      light: number;
      medium: number;
      subtle: number;
    };
    borderAlpha: {
      primary: number;
      accent: number;
      subtle: number;
    };
  };
  radius: {
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    xxl: number;
    pill: number;
  };
  animations: {
    instant: number;
    fast: number;
    normal: number;
    slow: number;
    verySlow: number;
    sequentialShort: number;
    sequentialMedium: number;
    sequentialLong: number;
    shimmer: number;
    sectionDelay: number;
    press: number;
  };
  sizes: {
    iconXs: number;
    iconSm: number;
    iconMd: number;
    iconLg: number;
    iconXl: number;
    avatarSm: number;
    avatarMd: number;
    avatarLg: number;
    avatarXl: number;
    statCardWidth: number;
    statCardHeight: number;
    quickActionWidth: number;
    quickActionHeight: number;
    appBarHeight: number;
    buttonHeightSm: number;
    buttonHeightMd: number;
    buttonHeightLg: number;
  };
  blur: {
    light: number;
    medium: number;
    strong: number;
    veryStrong: number;
  };
}

export const DEFAULT_DESIGN_TOKENS_CONFIG: DesignTokensConfig = {
  spacing: {
    xs: 4.0,
    sm: 8.0,
    md: 12.0,
    lg: 16.0,
    xl: 20.0,
    xxl: 24.0,
    xxxl: 32.0,
    huge: 40.0,
  },
  colors: {
    primary: "#6366F1",
    accent: "#D4AF37",
    secondary: "#64748B",
    gold: "#D4AF37",
    success: "#4CAF50",
    warning: "#FFC107",
    error: "#F44336",
    info: "#2196F3",
    textAlpha: {
      secondary: 0.8,
      tertiary: 0.6,
      disabled: 0.4,
    },
    glassAlpha: {
      light: 0.15,
      medium: 0.1,
      subtle: 0.05,
    },
    borderAlpha: {
      primary: 0.2,
      accent: 0.6,
      subtle: 0.1,
    },
  },
  radius: {
    xs: 8.0,
    sm: 12.0,
    md: 16.0,
    lg: 20.0,
    xl: 24.0,
    xxl: 28.0,
    pill: 100.0,
  },
  animations: {
    instant: 0,
    fast: 200,
    normal: 400,
    slow: 350,
    verySlow: 800,
    sequentialShort: 100,
    sequentialMedium: 150,
    sequentialLong: 200,
    shimmer: 1500,
    sectionDelay: 400,
    press: 80,
  },
  sizes: {
    iconXs: 16.0,
    iconSm: 20.0,
    iconMd: 24.0,
    iconLg: 32.0,
    iconXl: 40.0,
    avatarSm: 32.0,
    avatarMd: 40.0,
    avatarLg: 56.0,
    avatarXl: 80.0,
    statCardWidth: 140.0,
    statCardHeight: 120.0,
    quickActionWidth: 100.0,
    quickActionHeight: 120.0,
    appBarHeight: 56.0,
    buttonHeightSm: 40.0,
    buttonHeightMd: 48.0,
    buttonHeightLg: 56.0,
  },
  blur: {
    light: 15.0,
    medium: 25.0,
    strong: 40.0,
    veryStrong: 60.0,
  },
};

// ============================================================================
// TEMPLATE DEFINITION
// ============================================================================

export const DESIGN_TOKENS_TEMPLATE: Template = {
  id: "design-edc-tokens",
  name: "EDC Design Tokens",
  description: "Complete design token system with spacing, colors, radius, borders, animations, sizes, and blur",
  type: "file",
  source: DESIGN_TOKENS_SOURCE,
  output: {
    path: "lib/theme",
    filename: "app_theme_extensions",
    extension: "dart",
  },
};

export default DESIGN_TOKENS_TEMPLATE;
