/**
 * Glassmorphic Gradient System Template
 *
 * Extracted from: /Users/kcdacre8tor/edc-web/lib/theme/app_gradients.dart
 *
 * Complete gradient library for glassmorphic UI:
 * - 4 glass intensity levels (subtle, medium, strong, veryStrong)
 * - Status gradients (success, warning, error, info)
 * - Theme gradients (primary, gold accent)
 * - Background gradients (dark, light)
 * - Button gradients with disabled states
 * - Helper methods for custom gradients
 *
 * Uses Flutter 3.29+ withValues() API (not deprecated withOpacity)
 */

import type { Template } from "../../../core/types.js";

// ============================================================================
// HANDLEBARS TEMPLATE SOURCE
// ============================================================================

export const GLASS_GRADIENTS_SOURCE = `// GENERATED CODE - DO NOT MODIFY BY HAND
// Glassmorphic Gradient System
// Generated by offline-flutter-pwa-builder

import 'package:flutter/material.dart';

/// Centralized gradient definitions for consistent glassmorphic design
///
/// Usage:
/// \`\`\`dart
/// Container(
///   decoration: BoxDecoration(
///     gradient: AppGradients.glassMedium,
///     borderRadius: BorderRadius.circular(12),
///   ),
/// )
/// \`\`\`
class AppGradients {
  AppGradients._(); // Private constructor to prevent instantiation

  // ============================================================================
  // GLASS GRADIENTS (for glassmorphic UI elements)
  // ============================================================================

  /// Very subtle glass effect ({{glass.subtle.start}} -> {{glass.subtle.end}} alpha)
  /// Use for: Backgrounds, subtle overlays
  static const LinearGradient glassSubtle = LinearGradient(
    colors: [
      Color(0x{{hexAlpha glass.subtle.start}}FFFFFF), // White with {{glass.subtle.start}} alpha
      Color(0x{{hexAlpha glass.subtle.end}}FFFFFF), // White with {{glass.subtle.end}} alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  /// Medium glass effect ({{glass.medium.start}} -> {{glass.medium.end}} alpha)
  /// Use for: Cards, containers, most UI elements
  static const LinearGradient glassMedium = LinearGradient(
    colors: [
      Color(0x{{hexAlpha glass.medium.start}}FFFFFF), // White with {{glass.medium.start}} alpha
      Color(0x{{hexAlpha glass.medium.end}}FFFFFF), // White with {{glass.medium.end}} alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  /// Strong glass effect ({{glass.strong.start}} -> {{glass.strong.end}} alpha)
  /// Use for: Interactive elements, filter chips, active states
  static const LinearGradient glassStrong = LinearGradient(
    colors: [
      Color(0x{{hexAlpha glass.strong.start}}FFFFFF), // White with {{glass.strong.start}} alpha
      Color(0x{{hexAlpha glass.strong.end}}FFFFFF), // White with {{glass.strong.end}} alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  /// Very strong glass effect ({{glass.veryStrong.start}} -> {{glass.veryStrong.end}} alpha)
  /// Use for: Emphasized containers, highlighted elements
  static const LinearGradient glassVeryStrong = LinearGradient(
    colors: [
      Color(0x{{hexAlpha glass.veryStrong.start}}FFFFFF), // White with {{glass.veryStrong.start}} alpha
      Color(0x{{hexAlpha glass.veryStrong.end}}FFFFFF), // White with {{glass.veryStrong.end}} alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  // ============================================================================
  // THEME GRADIENTS (using app colors)
  // ============================================================================

  /// Primary theme gradient (primary -> accent)
  /// Use for: Primary buttons, key actions, progress indicators
  static const LinearGradient primary = LinearGradient(
    colors: [
      {{flutterColor colors.primary}}, // Primary color
      {{flutterColor colors.accent}}, // Accent color
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  {{#if colors.gold}}
  /// Gold accent gradient (subtle gold overlay)
  /// Use for: User-related elements, profile sections, achievements
  static const LinearGradient goldAccent = LinearGradient(
    colors: [
      Color(0x4D{{hexColor colors.gold}}), // Gold with 0.30 alpha
      Color(0x1A{{hexColor colors.gold}}), // Gold with 0.10 alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  /// Gold accent for borders (stronger)
  /// Use for: Borders, outlines, highlights
  static const LinearGradient goldBorder = LinearGradient(
    colors: [
      Color(0x99{{hexColor colors.gold}}), // Gold with 0.60 alpha
      Color(0x66{{hexColor colors.gold}}), // Gold with 0.40 alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );
  {{/if}}

  // ============================================================================
  // BACKGROUND GRADIENTS
  // ============================================================================

  /// Dark background gradient (navy -> deep blue -> dark purple)
  /// Use for: Main app background (GradientBackground widget)
  static const LinearGradient backgroundDark = LinearGradient(
    colors: [
      {{flutterColor background.dark.start}}, // Dark navy
      {{flutterColor background.dark.middle}}, // Deep blue
      {{flutterColor background.dark.end}}, // Dark purple
    ],
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
  );

  /// Light background gradient (off-white -> light blue)
  /// Use for: Light mode background
  static const LinearGradient backgroundLight = LinearGradient(
    colors: [
      {{flutterColor background.light.start}}, // Off-white
      {{flutterColor background.light.end}}, // Light blue
    ],
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
  );

  // ============================================================================
  // BUTTON GRADIENTS
  // ============================================================================

  /// Button gradient (glass medium for enabled state)
  /// Use for: Default button backgrounds
  static const LinearGradient button = glassMedium;

  /// Button gradient disabled state (very subtle)
  /// Use for: Disabled buttons
  static const LinearGradient buttonDisabled = LinearGradient(
    colors: [
      Color(0x1A808080), // Gray with 0.10 alpha
      Color(0x0D808080), // Gray with 0.05 alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  // ============================================================================
  // STATUS GRADIENTS (for different states)
  // ============================================================================

  /// Success gradient (green overlay)
  /// Use for: Success messages, completed states
  static const LinearGradient success = LinearGradient(
    colors: [
      Color(0x4D{{hexColor status.success}}), // Green with 0.30 alpha
      Color(0x1A{{hexColor status.success}}), // Green with 0.10 alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  /// Warning gradient (orange overlay)
  /// Use for: Warning messages, caution states
  static const LinearGradient warning = LinearGradient(
    colors: [
      Color(0x4D{{hexColor status.warning}}), // Orange with 0.30 alpha
      Color(0x1A{{hexColor status.warning}}), // Orange with 0.10 alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  /// Error gradient (red overlay)
  /// Use for: Error messages, delete actions
  static const LinearGradient error = LinearGradient(
    colors: [
      Color(0x4D{{hexColor status.error}}), // Red with 0.30 alpha
      Color(0x1A{{hexColor status.error}}), // Red with 0.10 alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  /// Info gradient (blue overlay)
  /// Use for: Info messages, help states
  static const LinearGradient info = LinearGradient(
    colors: [
      Color(0x4D{{hexColor status.info}}), // Blue with 0.30 alpha
      Color(0x1A{{hexColor status.info}}), // Blue with 0.10 alpha
    ],
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
  );

  // ============================================================================
  // HELPER METHODS
  // ============================================================================

  /// Create a custom glass gradient with specified alpha values
  ///
  /// Example:
  /// \`\`\`dart
  /// final customGlass = AppGradients.customGlass(0.18, 0.09);
  /// \`\`\`
  static LinearGradient customGlass(double startAlpha, double endAlpha) {
    return LinearGradient(
      colors: [
        Color.fromRGBO(255, 255, 255, startAlpha),
        Color.fromRGBO(255, 255, 255, endAlpha),
      ],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    );
  }

  /// Create a custom colored gradient with specified color and alpha values
  /// Uses Flutter 3.29+ withValues() API
  ///
  /// Example:
  /// \`\`\`dart
  /// final customColor = AppGradients.customColored(
  ///   Colors.purple,
  ///   startAlpha: 0.30,
  ///   endAlpha: 0.10,
  /// );
  /// \`\`\`
  static LinearGradient customColored(
    Color color, {
    double startAlpha = 0.30,
    double endAlpha = 0.10,
  }) {
    return LinearGradient(
      colors: [
        color.withValues(alpha: startAlpha),
        color.withValues(alpha: endAlpha),
      ],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    );
  }

  /// Create a radial gradient for spotlight effects
  ///
  /// Example:
  /// \`\`\`dart
  /// final spotlight = AppGradients.spotlight(Colors.white, 0.3);
  /// \`\`\`
  static RadialGradient spotlight(
    Color color,
    double maxAlpha, {
    double radius = 0.8,
  }) {
    return RadialGradient(
      colors: [
        color.withValues(alpha: maxAlpha),
        color.withValues(alpha: 0.0),
      ],
      radius: radius,
    );
  }

  /// Get glass gradient by intensity level (0-3)
  /// 0 = subtle, 1 = medium, 2 = strong, 3 = veryStrong
  static LinearGradient getGlassByLevel(int level) {
    switch (level) {
      case 0:
        return glassSubtle;
      case 1:
        return glassMedium;
      case 2:
        return glassStrong;
      case 3:
        return glassVeryStrong;
      default:
        return glassMedium;
    }
  }

  /// Get status gradient by type
  static LinearGradient getStatusGradient(String type) {
    switch (type.toLowerCase()) {
      case 'success':
        return success;
      case 'warning':
        return warning;
      case 'error':
        return error;
      case 'info':
        return info;
      default:
        return info;
    }
  }
}
`;

// ============================================================================
// DEFAULT VALUES FOR HANDLEBARS CONTEXT
// ============================================================================

export interface GlassGradientsConfig {
  glass: {
    subtle: { start: number; end: number };
    medium: { start: number; end: number };
    strong: { start: number; end: number };
    veryStrong: { start: number; end: number };
  };
  colors: {
    primary: string;
    accent: string;
    gold?: string;
  };
  background: {
    dark: {
      start: string;
      middle: string;
      end: string;
    };
    light: {
      start: string;
      end: string;
    };
  };
  status: {
    success: string;
    warning: string;
    error: string;
    info: string;
  };
}

export const DEFAULT_GLASS_GRADIENTS_CONFIG: GlassGradientsConfig = {
  glass: {
    subtle: { start: 0.10, end: 0.05 },
    medium: { start: 0.15, end: 0.08 },
    strong: { start: 0.20, end: 0.10 },
    veryStrong: { start: 0.25, end: 0.15 },
  },
  colors: {
    primary: "#6366F1",
    accent: "#8B5CF6",
    gold: "#D4AF37",
  },
  background: {
    dark: {
      start: "#1A1A2E",
      middle: "#16213E",
      end: "#0F3460",
    },
    light: {
      start: "#F8FAFF",
      end: "#E8F2FF",
    },
  },
  status: {
    success: "#4CAF50",
    warning: "#FFA726",
    error: "#F44336",
    info: "#2196F3",
  },
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Convert alpha value (0-1) to 2-digit hex string
 * Example: 0.15 -> "26" (26 in hex = 38 in decimal = 15% of 255)
 */
export function alphaToHex(alpha: number): string {
  const value = Math.round(alpha * 255);
  return value.toString(16).padStart(2, "0").toUpperCase();
}

/**
 * Extract hex color without # prefix
 * Example: "#D4AF37" -> "D4AF37"
 */
export function extractHexColor(hex: string): string {
  return hex.replace("#", "").toUpperCase();
}

// ============================================================================
// TEMPLATE DEFINITION
// ============================================================================

export const GLASS_GRADIENTS_TEMPLATE: Template = {
  id: "design-glass-gradients",
  name: "Glassmorphic Gradients",
  description: "4-level glass gradient system with status gradients and helper methods",
  type: "file",
  source: GLASS_GRADIENTS_SOURCE,
  output: {
    path: "lib/theme",
    filename: "app_gradients",
    extension: "dart",
  },
};

export default GLASS_GRADIENTS_TEMPLATE;
