/**
 * EDC Light Simulation Template
 *
 * Extracted from glass_container foreground decoration pattern
 * Common across: glass_card.dart, glass_button.dart, dark_glass_container.dart,
 *                base_bottom_sheet.dart, verse_bottom_sheet.dart
 *
 * Light simulation creates realistic glass effects by adding a gradient
 * overlay that simulates light hitting the top of a glass surface.
 *
 * Applied via BoxDecoration.foregroundDecoration for layered effect.
 */

import type { Template } from "../../../core/types.js";

// ============================================================================
// HANDLEBARS TEMPLATE SOURCE
// ============================================================================

export const LIGHT_SIMULATION_SOURCE = `// GENERATED CODE - DO NOT MODIFY BY HAND
// EDC Light Simulation System
// Generated by offline-flutter-pwa-builder

import 'package:flutter/material.dart';

// ============================================================================
// LIGHT SIMULATION - Realistic glass lighting effects
// ============================================================================

/// Light simulation system for creating realistic glass effects
/// Simulates light hitting the top of glass surfaces via gradient overlays
class AppLightSimulation {
  const AppLightSimulation();

  /// Creates a light simulation BoxDecoration for foreground overlay
  ///
  /// Apply to Container via foregroundDecoration parameter:
  ///
  /// Container(
  ///   decoration: BoxDecoration(...), // Background
  ///   foregroundDecoration: AppLightSimulation.createDecoration(
  ///     borderRadius: BorderRadius.circular(20),
  ///   ),
  ///   child: child,
  /// )
  static BoxDecoration createDecoration({
    required BorderRadius borderRadius,
    double intensity = {{defaultIntensity}},
    Alignment begin = Alignment.topCenter,
    Alignment end = Alignment.bottomCenter,
    List<double> stops = const [{{defaultStopStart}}, {{defaultStopEnd}}],
  }) {
    return BoxDecoration(
      borderRadius: borderRadius,
      gradient: LinearGradient(
        begin: begin,
        end: end,
        stops: stops,
        colors: [
          Colors.white.withValues(alpha: intensity),
          Colors.transparent,
        ],
      ),
    );
  }

  /// Standard light simulation (top-to-bottom fade)
  static BoxDecoration standard(BorderRadius borderRadius) {
    return createDecoration(
      borderRadius: borderRadius,
      intensity: {{defaultIntensity}},
    );
  }

  /// Subtle light simulation (lower intensity)
  static BoxDecoration subtle(BorderRadius borderRadius) {
    return createDecoration(
      borderRadius: borderRadius,
      intensity: {{presets.subtle.intensity}},
    );
  }

  /// Strong light simulation (higher intensity)
  static BoxDecoration strong(BorderRadius borderRadius) {
    return createDecoration(
      borderRadius: borderRadius,
      intensity: {{presets.strong.intensity}},
    );
  }

  /// Reversed light simulation (bottom-to-top)
  static BoxDecoration reversed(BorderRadius borderRadius) {
    return createDecoration(
      borderRadius: borderRadius,
      intensity: {{defaultIntensity}},
      begin: Alignment.bottomCenter,
      end: Alignment.topCenter,
    );
  }

  /// Diagonal light simulation (top-left to bottom-right)
  static BoxDecoration diagonal(BorderRadius borderRadius) {
    return createDecoration(
      borderRadius: borderRadius,
      intensity: {{defaultIntensity}},
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    );
  }

  /// Extended fade (longer gradient transition)
  static BoxDecoration extended(BorderRadius borderRadius) {
    return createDecoration(
      borderRadius: borderRadius,
      intensity: {{defaultIntensity}},
      stops: [{{presets.extended.stopStart}}, {{presets.extended.stopEnd}}],
    );
  }

  /// Short fade (quick transition)
  static BoxDecoration short(BorderRadius borderRadius) {
    return createDecoration(
      borderRadius: borderRadius,
      intensity: {{defaultIntensity}},
      stops: [{{presets.short.stopStart}}, {{presets.short.stopEnd}}],
    );
  }
}

// ============================================================================
// LIGHT SIMULATION MIXIN - For easy integration into widgets
// ============================================================================

/// Mixin for widgets that support light simulation
///
/// Usage:
///
/// class MyGlassWidget extends StatelessWidget with LightSimulationMixin {
///   final bool enableLightSimulation;
///   final double borderRadius;
///
///   BoxDecoration? get foregroundDecoration =>
///       getLightSimulation(enableLightSimulation, borderRadius);
/// }
mixin LightSimulationMixin {
  BoxDecoration? getLightSimulation(
    bool enabled,
    double borderRadius, {
    double intensity = {{defaultIntensity}},
  }) {
    if (!enabled) return null;

    return AppLightSimulation.createDecoration(
      borderRadius: BorderRadius.circular(borderRadius),
      intensity: intensity,
    );
  }

  BoxDecoration? getLightSimulationWithRadius(
    bool enabled,
    BorderRadius borderRadius, {
    double intensity = {{defaultIntensity}},
  }) {
    if (!enabled) return null;

    return AppLightSimulation.createDecoration(
      borderRadius: borderRadius,
      intensity: intensity,
    );
  }
}
`;

// ============================================================================
// LIGHT SIMULATION CONFIG INTERFACE
// ============================================================================

export interface LightSimulationPreset {
  intensity: number;
  stopStart?: number;
  stopEnd?: number;
}

export interface LightSimulationConfig {
  defaultIntensity: number;
  defaultStopStart: number;
  defaultStopEnd: number;
  presets: {
    subtle: LightSimulationPreset;
    strong: LightSimulationPreset;
    extended: LightSimulationPreset;
    short: LightSimulationPreset;
  };
}

// ============================================================================
// DEFAULT VALUES
// ============================================================================

export const DEFAULT_LIGHT_CONFIG: LightSimulationConfig = {
  defaultIntensity: 0.15,
  defaultStopStart: 0.0,
  defaultStopEnd: 0.5,
  presets: {
    subtle: {
      intensity: 0.08,
    },
    strong: {
      intensity: 0.25,
    },
    extended: {
      intensity: 0.15,
      stopStart: 0.0,
      stopEnd: 0.7,
    },
    short: {
      intensity: 0.15,
      stopStart: 0.0,
      stopEnd: 0.3,
    },
  },
};

// ============================================================================
// TEMPLATE DEFINITION
// ============================================================================

export const LIGHT_SIMULATION_TEMPLATE: Template = {
  id: "design-edc-light-simulation",
  name: "EDC Light Simulation System",
  description: "Light simulation system for realistic glass effects via foreground gradient overlays",
  type: "file",
  source: LIGHT_SIMULATION_SOURCE,
  output: {
    path: "lib/theme",
    filename: "app_light_simulation",
    extension: "dart",
  },
};

export default LIGHT_SIMULATION_TEMPLATE;
