/**
 * EDC Noise Overlay Template
 *
 * Extracted from: /Users/kcdacre8tor/edc-web/lib/widgets/noise_overlay.dart
 *
 * StaticNoiseOverlay widget adds subtle grain texture to glass surfaces
 * for realistic glass effects. Uses seeded Random(42) for consistency
 * across rebuilds.
 *
 * Implements CustomPainter for efficient rendering of noise particles.
 */

import type { Template } from "../../../core/types.js";

// ============================================================================
// HANDLEBARS TEMPLATE SOURCE
// ============================================================================

export const NOISE_OVERLAY_SOURCE = `// GENERATED CODE - DO NOT MODIFY BY HAND
// EDC Noise Overlay Widget
// Generated by offline-flutter-pwa-builder

import 'dart:math';
import 'package:flutter/material.dart';

// ============================================================================
// STATIC NOISE OVERLAY - Adds grain texture to glass surfaces
// ============================================================================

/// StaticNoiseOverlay - Adds subtle grain texture to glass surfaces
///
/// Creates a realistic glass effect by applying a random static noise pattern.
/// The noise is deterministic (seeded) so it stays consistent across rebuilds.
///
/// Usage:
///
/// StaticNoiseOverlay(
///   opacity: 0.06,
///   density: 0.3,
///   child: YourWidget(),
/// )
class StaticNoiseOverlay extends StatelessWidget {
  final Widget child;
  final double opacity;
  final double density;

  const StaticNoiseOverlay({
    super.key,
    required this.child,
    this.opacity = {{defaultOpacity}},
    this.density = {{defaultDensity}},
  });

  @override
  Widget build(BuildContext context) {
    return Stack(
      fit: StackFit.passthrough,
      children: [
        child,
        Positioned.fill(
          child: IgnorePointer(
            child: CustomPaint(
              painter: _StaticNoisePainter(
                opacity: opacity,
                density: density,
              ),
            ),
          ),
        ),
      ],
    );
  }
}

// ============================================================================
// NOISE PAINTER - CustomPainter for efficient noise rendering
// ============================================================================

class _StaticNoisePainter extends CustomPainter {
  final double opacity;
  final double density;
  final Random _random = Random({{seed}}); // Seeded for consistency

  _StaticNoisePainter({
    required this.opacity,
    required this.density,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()..strokeWidth = {{particleSize}};
    final pointCount = (size.width * size.height * density / 100).toInt();

    for (int i = 0; i < pointCount; i++) {
      final x = _random.nextDouble() * size.width;
      final y = _random.nextDouble() * size.height;
      final brightness = _random.nextDouble();
      paint.color = Colors.white.withValues(alpha: brightness * opacity);
      canvas.drawCircle(Offset(x, y), {{particleSize}}, paint);
    }
  }

  @override
  bool shouldRepaint(_StaticNoisePainter oldDelegate) {
    return oldDelegate.opacity != opacity || oldDelegate.density != density;
  }
}

// ============================================================================
// NOISE PRESETS - Common noise configurations
// ============================================================================

/// Pre-configured noise overlay presets
class NoisePresets {
  const NoisePresets();

  /// Very subtle noise for minimal texture
  static Widget verySubtle({required Widget child}) {
    return StaticNoiseOverlay(
      opacity: 0.03,
      density: 0.2,
      child: child,
    );
  }

  /// Subtle noise (default) - balanced for most use cases
  static Widget subtle({required Widget child}) {
    return StaticNoiseOverlay(
      opacity: {{defaultOpacity}},
      density: {{defaultDensity}},
      child: child,
    );
  }

  /// Medium noise for noticeable texture
  static Widget medium({required Widget child}) {
    return StaticNoiseOverlay(
      opacity: 0.09,
      density: 0.4,
      child: child,
    );
  }

  /// Strong noise for pronounced grain effect
  static Widget strong({required Widget child}) {
    return StaticNoiseOverlay(
      opacity: 0.12,
      density: 0.5,
      child: child,
    );
  }
}
`;

// ============================================================================
// NOISE OVERLAY CONFIG INTERFACE
// ============================================================================

export interface NoiseOverlayConfig {
  defaultOpacity: number;
  defaultDensity: number;
  seed: number;
  particleSize: number;
}

// ============================================================================
// DEFAULT VALUES
// ============================================================================

export const DEFAULT_NOISE_CONFIG: NoiseOverlayConfig = {
  defaultOpacity: 0.06,
  defaultDensity: 0.3,
  seed: 42, // Seeded for consistency across rebuilds
  particleSize: 0.5,
};

// ============================================================================
// TEMPLATE DEFINITION
// ============================================================================

export const NOISE_OVERLAY_TEMPLATE: Template = {
  id: "design-edc-noise-overlay",
  name: "EDC Noise Overlay Widget",
  description: "StaticNoiseOverlay widget for adding grain texture to glass surfaces with seeded random for consistency",
  type: "file",
  source: NOISE_OVERLAY_SOURCE,
  output: {
    path: "lib/widgets",
    filename: "noise_overlay",
    extension: "dart",
  },
};

export default NOISE_OVERLAY_TEMPLATE;
