/**
 * EDC Shadow System Template
 *
 * Extracted from: /Users/kcdacre8tor/edc-web/lib/theme/app_theme.dart (lines 233-257)
 *
 * Dual shadow system for glassmorphic effects:
 * - glass: Dual shadows (ambient + definition) for glass surfaces
 * - card: Subtle shadow for elevated cards
 * - elevated: Stronger shadow with primary color tint
 *
 * Each shadow type uses dual shadows:
 * - Ambient shadow: Far, soft, provides depth
 * - Definition shadow: Close, sharp, provides separation
 */

import type { Template } from "../../../core/types.js";

// ============================================================================
// HANDLEBARS TEMPLATE SOURCE
// ============================================================================

export const SHADOW_SYSTEM_SOURCE = `// GENERATED CODE - DO NOT MODIFY BY HAND
// EDC Shadow System
// Generated by offline-flutter-pwa-builder

import 'package:flutter/material.dart';

// ============================================================================
// SHADOW SYSTEM - Dual shadow approach for realistic depth
// ============================================================================

/// Shadow system for glassmorphic and elevated components
/// Each shadow type uses dual shadows for realistic lighting:
/// - Ambient shadow: Far offset, soft blur (atmospheric depth)
/// - Definition shadow: Close offset, sharp edges (object separation)
class AppShadows {
  const AppShadows();

  // Glass surface shadows - dual shadow for realistic glass depth
  static final List<BoxShadow> glass = [
    // Ambient shadow - atmospheric depth
    BoxShadow(
      color: Colors.black.withValues(alpha: {{glass.ambient.alpha}}),
      blurRadius: {{glass.ambient.blur}},
      offset: Offset({{glass.ambient.offsetX}}, {{glass.ambient.offsetY}}),
    ),
    // Definition shadow - sharp edges
    BoxShadow(
      color: Colors.black.withValues(alpha: {{glass.definition.alpha}}),
      blurRadius: {{glass.definition.blur}},
      offset: Offset({{glass.definition.offsetX}}, {{glass.definition.offsetY}}),
    ),
  ];

  // Card shadows - subtle elevation
  static final List<BoxShadow> card = [
    // Ambient shadow
    BoxShadow(
      color: Colors.black.withValues(alpha: {{card.ambient.alpha}}),
      blurRadius: {{card.ambient.blur}},
      offset: Offset({{card.ambient.offsetX}}, {{card.ambient.offsetY}}),
    ),
    // Definition shadow
    BoxShadow(
      color: Colors.black.withValues(alpha: {{card.definition.alpha}}),
      blurRadius: {{card.definition.blur}},
      offset: Offset({{card.definition.offsetX}}, {{card.definition.offsetY}}),
    ),
  ];

  // Elevated shadows - stronger shadow with primary color tint
  static final List<BoxShadow> elevated = [
    // Ambient shadow with color tint
    BoxShadow(
      color: {{flutterColor primaryColor}}.withValues(alpha: {{elevated.ambient.alpha}}),
      blurRadius: {{elevated.ambient.blur}},
      offset: Offset({{elevated.ambient.offsetX}}, {{elevated.ambient.offsetY}}),
    ),
    // Definition shadow
    BoxShadow(
      color: Colors.black.withValues(alpha: {{elevated.definition.alpha}}),
      blurRadius: {{elevated.definition.blur}},
      offset: Offset({{elevated.definition.offsetX}}, {{elevated.definition.offsetY}}),
    ),
  ];

  // Single shadow variants (backward compatibility)
  static final List<BoxShadow> glassSimple = [glass.first];
  static final List<BoxShadow> cardSimple = [card.first];
  static final List<BoxShadow> elevatedSimple = [elevated.first];
}
`;

// ============================================================================
// SHADOW CONFIG INTERFACE
// ============================================================================

export interface ShadowConfig {
  alpha: number;
  blur: number;
  offsetX: number;
  offsetY: number;
}

export interface ShadowSystemConfig {
  glass: {
    ambient: ShadowConfig;
    definition: ShadowConfig;
  };
  card: {
    ambient: ShadowConfig;
    definition: ShadowConfig;
  };
  elevated: {
    ambient: ShadowConfig;
    definition: ShadowConfig;
  };
  primaryColor: string;
}

// ============================================================================
// DEFAULT VALUES
// ============================================================================

export const DEFAULT_SHADOW_CONFIG: ShadowSystemConfig = {
  glass: {
    ambient: {
      alpha: 0.1,
      blur: 20.0,
      offsetX: 0,
      offsetY: 10,
    },
    definition: {
      alpha: 0.05,
      blur: 8.0,
      offsetX: 0,
      offsetY: 4,
    },
  },
  card: {
    ambient: {
      alpha: 0.05,
      blur: 10.0,
      offsetX: 0,
      offsetY: 4,
    },
    definition: {
      alpha: 0.02,
      blur: 4.0,
      offsetX: 0,
      offsetY: 2,
    },
  },
  elevated: {
    ambient: {
      alpha: 0.2,
      blur: 20.0,
      offsetX: 0,
      offsetY: 8,
    },
    definition: {
      alpha: 0.08,
      blur: 10.0,
      offsetX: 0,
      offsetY: 4,
    },
  },
  primaryColor: "#6366F1",
};

// ============================================================================
// TEMPLATE DEFINITION
// ============================================================================

export const SHADOW_SYSTEM_TEMPLATE: Template = {
  id: "design-edc-shadows",
  name: "EDC Shadow System",
  description: "Dual shadow system for glassmorphic effects with ambient and definition shadows",
  type: "file",
  source: SHADOW_SYSTEM_SOURCE,
  output: {
    path: "lib/theme",
    filename: "app_shadows",
    extension: "dart",
  },
};

export default SHADOW_SYSTEM_TEMPLATE;
