/**
 * EDC Text Shadow System Template
 *
 * Extracted from: /Users/kcdacre8tor/edc-web/lib/theme/app_theme.dart (lines 258-318)
 *
 * 4-level text shadow system for readable text on glass/gradient backgrounds:
 * - subtle: 15% opacity - for subheadings
 * - medium: 30% opacity - for headings
 * - strong: 40% opacity - for emphasized text
 * - bold: 50% opacity - for maximum contrast
 *
 * Pre-styled text styles optimized for glass components included.
 */

import type { Template } from "../../../core/types.js";

// ============================================================================
// HANDLEBARS TEMPLATE SOURCE
// ============================================================================

export const TEXT_SHADOW_SOURCE = `// GENERATED CODE - DO NOT MODIFY BY HAND
// EDC Text Shadow System
// Generated by offline-flutter-pwa-builder

import 'package:flutter/material.dart';

// ============================================================================
// TEXT SHADOW SYSTEM - 4-level hierarchy for readable text on glass
// ============================================================================

/// Text shadow system for readable text on glass and gradient backgrounds
/// 4 levels of shadow intensity for different text hierarchy levels
class AppTextShadows {
  const AppTextShadows();

  // Subtle shadow - 15% opacity for secondary text
  static const List<Shadow> subtle = [
    Shadow(
      color: Color(0x26000000), // 15% black opacity
      offset: Offset({{subtle.offsetX}}, {{subtle.offsetY}}),
      blurRadius: {{subtle.blur}},
    ),
  ];

  // Medium shadow - 30% opacity for primary headings
  static const List<Shadow> medium = [
    Shadow(
      color: Color(0x4D000000), // 30% black opacity
      offset: Offset({{medium.offsetX}}, {{medium.offsetY}}),
      blurRadius: {{medium.blur}},
    ),
  ];

  // Strong shadow - 40% opacity for emphasized text
  static const List<Shadow> strong = [
    Shadow(
      color: Color(0x66000000), // 40% black opacity
      offset: Offset({{strong.offsetX}}, {{strong.offsetY}}),
      blurRadius: {{strong.blur}},
    ),
  ];

  // Bold shadow - 50% opacity for maximum contrast
  static const List<Shadow> bold = [
    Shadow(
      color: Color(0x80000000), // 50% black opacity
      offset: Offset({{bold.offsetX}}, {{bold.offsetY}}),
      blurRadius: {{bold.blur}},
    ),
  ];

  // Dual shadow for extreme contrast (optional)
  static const List<Shadow> dualBold = [
    Shadow(
      color: Color(0x80000000), // 50% opacity
      offset: Offset({{bold.offsetX}}, {{bold.offsetY}}),
      blurRadius: {{bold.blur}},
    ),
    Shadow(
      color: Color(0x26000000), // 15% opacity ambient
      offset: Offset(0, {{bold.offsetY}} * 2),
      blurRadius: {{bold.blur}} * 1.5,
    ),
  ];
}

// ============================================================================
// PRE-STYLED TEXT STYLES - Ready-to-use styles for glass components
// ============================================================================

/// Pre-configured text styles optimized for glass backgrounds
class AppTextStyles {
  const AppTextStyles();

  // Heading style - large, bold, medium shadow
  static const TextStyle heading = TextStyle(
    fontSize: {{styles.heading.fontSize}},
    fontWeight: FontWeight.{{styles.heading.fontWeight}},
    color: {{flutterColor styles.heading.color}},
    shadows: AppTextShadows.medium,
    {{#if styles.heading.letterSpacing}}
    letterSpacing: {{styles.heading.letterSpacing}},
    {{/if}}
  );

  // Subheading style - medium size, semi-bold, subtle shadow
  static const TextStyle subheading = TextStyle(
    fontSize: {{styles.subheading.fontSize}},
    fontWeight: FontWeight.{{styles.subheading.fontWeight}},
    color: {{flutterColor styles.subheading.color}},
    shadows: AppTextShadows.subtle,
    {{#if styles.subheading.letterSpacing}}
    letterSpacing: {{styles.subheading.letterSpacing}},
    {{/if}}
  );

  // Body style - normal size, no shadow (sufficient contrast)
  static const TextStyle body = TextStyle(
    fontSize: {{styles.body.fontSize}},
    fontWeight: FontWeight.{{styles.body.fontWeight}},
    height: {{styles.body.lineHeight}},
    color: {{flutterColor styles.body.color}},
    {{#if styles.body.letterSpacing}}
    letterSpacing: {{styles.body.letterSpacing}},
    {{/if}}
  );

  // Caption style - small, no shadow
  static const TextStyle caption = TextStyle(
    fontSize: {{styles.caption.fontSize}},
    fontWeight: FontWeight.{{styles.caption.fontWeight}},
    color: {{flutterColor styles.caption.color}},
    {{#if styles.caption.letterSpacing}}
    letterSpacing: {{styles.caption.letterSpacing}},
    {{/if}}
  );

  // Display style - extra large for hero text
  static const TextStyle display = TextStyle(
    fontSize: {{styles.display.fontSize}},
    fontWeight: FontWeight.{{styles.display.fontWeight}},
    color: {{flutterColor styles.display.color}},
    shadows: AppTextShadows.bold,
    {{#if styles.display.letterSpacing}}
    letterSpacing: {{styles.display.letterSpacing}},
    {{/if}}
  );
}
`;

// ============================================================================
// TEXT SHADOW CONFIG INTERFACE
// ============================================================================

export interface TextShadowLevel {
  offsetX: number;
  offsetY: number;
  blur: number;
}

export interface TextStyleConfig {
  fontSize: number;
  fontWeight: string;
  color: string;
  letterSpacing?: number;
  lineHeight?: number;
}

export interface TextShadowConfig {
  subtle: TextShadowLevel;
  medium: TextShadowLevel;
  strong: TextShadowLevel;
  bold: TextShadowLevel;
  styles: {
    heading: TextStyleConfig;
    subheading: TextStyleConfig;
    body: TextStyleConfig & { lineHeight: number };
    caption: TextStyleConfig;
    display: TextStyleConfig;
  };
}

// ============================================================================
// DEFAULT VALUES
// ============================================================================

export const DEFAULT_TEXT_SHADOW_CONFIG: TextShadowConfig = {
  subtle: {
    offsetX: 0,
    offsetY: 1,
    blur: 2.0,
  },
  medium: {
    offsetX: 0,
    offsetY: 1,
    blur: 3.0,
  },
  strong: {
    offsetX: 0,
    offsetY: 2,
    blur: 4.0,
  },
  bold: {
    offsetX: 0,
    offsetY: 2,
    blur: 6.0,
  },
  styles: {
    heading: {
      fontSize: 28,
      fontWeight: "bold",
      color: "#FFFFFF",
    },
    subheading: {
      fontSize: 20,
      fontWeight: "w600",
      color: "#FFFFFF",
    },
    body: {
      fontSize: 16,
      fontWeight: "normal",
      color: "#FFFFFF",
      lineHeight: 1.5,
    },
    caption: {
      fontSize: 14,
      fontWeight: "w500",
      color: "#B0B0B0",
    },
    display: {
      fontSize: 40,
      fontWeight: "bold",
      color: "#FFFFFF",
      letterSpacing: -0.5,
    },
  },
};

// ============================================================================
// TEMPLATE DEFINITION
// ============================================================================

export const TEXT_SHADOW_TEMPLATE: Template = {
  id: "design-edc-text-shadows",
  name: "EDC Text Shadow System",
  description: "4-level text shadow system with pre-styled text styles for glass backgrounds",
  type: "file",
  source: TEXT_SHADOW_SOURCE,
  output: {
    path: "lib/theme",
    filename: "app_text_shadows",
    extension: "dart",
  },
};

export default TEXT_SHADOW_TEMPLATE;
