/**
 * WCAG Contrast Calculator Template
 *
 * Extracted from: /Users/kcdacre8tor/edc-web/lib/theme/app_theme.dart (lines 367-443)
 *
 * WCAG 2.1 compliant contrast ratio calculator:
 * - _relativeLuminance(): Calculate relative luminance using sRGB gamma correction
 * - contrastRatio(): Calculate contrast ratio between two colors
 * - meetsWcagAA(): Check if contrast meets WCAG AA (4.5:1 for normal text)
 * - meetsWcagAALarge(): Check if contrast meets WCAG AA for large text (3:1)
 * - meetsWcagAAA(): Check if contrast meets WCAG AAA (7:1 for normal text)
 * - getContrastReport(): Get formatted contrast report string
 * - verifyThemeContrast(): Debug helper to verify app theme colors
 *
 * Integrates with accessibility module for WCAG auditing
 */

import type { Template } from "../../../core/types.js";

// ============================================================================
// HANDLEBARS TEMPLATE SOURCE
// ============================================================================

export const WCAG_CONTRAST_SOURCE = `// GENERATED CODE - DO NOT MODIFY BY HAND
// WCAG Contrast Calculator
// Generated by offline-flutter-pwa-builder

import 'dart:math';
import 'package:flutter/material.dart';

/// WCAG Contrast Ratio Calculator for Accessibility
///
/// Verifies color contrast meets WCAG 2.1 Level AA/AAA standards:
/// - Normal text: 4.5:1 minimum (AA), 7:1 (AAA)
/// - Large text (>=18pt or >=14pt bold): 3:1 minimum (AA)
/// - UI components and graphical objects: 3:1 minimum
///
/// Usage:
/// \`\`\`dart
/// // Check if colors meet WCAG AA
/// final passes = WCAGContrast.meetsWcagAA(Colors.white, Colors.blue);
///
/// // Get detailed report
/// final report = WCAGContrast.getContrastReport(Colors.white, Colors.blue);
/// print(report); // "4.50:1 [AA Pass] [AAA Fail]"
/// \`\`\`
class WCAGContrast {
  WCAGContrast._(); // Private constructor - static methods only

  // ============================================================================
  // WCAG THRESHOLDS
  // ============================================================================

  /// WCAG AA minimum contrast ratio for normal text
  static const double wcagAANormalText = 4.5;

  /// WCAG AA minimum contrast ratio for large text (>=18pt or >=14pt bold)
  static const double wcagAALargeText = 3.0;

  /// WCAG AAA minimum contrast ratio for normal text
  static const double wcagAAANormalText = 7.0;

  /// WCAG AAA minimum contrast ratio for large text
  static const double wcagAAALargeText = 4.5;

  /// Minimum contrast ratio for UI components and graphical objects
  static const double wcagUIComponents = 3.0;

  // ============================================================================
  // CORE CALCULATIONS
  // ============================================================================

  /// Calculate relative luminance using WCAG formula
  ///
  /// Implements WCAG 2.1 relative luminance calculation:
  /// https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html
  ///
  /// Uses sRGB gamma correction formula:
  /// - If value <= 0.03928: value / 12.92
  /// - Else: ((value + 0.055) / 1.055) ^ 2.4
  static double _relativeLuminance(Color color) {
    double r = color.red / 255.0;
    double g = color.green / 255.0;
    double b = color.blue / 255.0;

    // Apply sRGB gamma correction
    r = (r <= 0.03928) ? r / 12.92 : pow((r + 0.055) / 1.055, 2.4).toDouble();
    g = (g <= 0.03928) ? g / 12.92 : pow((g + 0.055) / 1.055, 2.4).toDouble();
    b = (b <= 0.03928) ? b / 12.92 : pow((b + 0.055) / 1.055, 2.4).toDouble();

    // Calculate luminance using ITU-R BT.709 coefficients
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
  }

  /// Calculate contrast ratio between two colors
  ///
  /// Returns a value between 1:1 (no contrast) and 21:1 (maximum contrast).
  /// The formula is: (L1 + 0.05) / (L2 + 0.05) where L1 is the lighter color.
  ///
  /// Example:
  /// \`\`\`dart
  /// final ratio = WCAGContrast.contrastRatio(Colors.white, Colors.black);
  /// print(ratio); // 21.0 (maximum contrast)
  /// \`\`\`
  static double contrastRatio(Color foreground, Color background) {
    double lum1 = _relativeLuminance(foreground) + 0.05;
    double lum2 = _relativeLuminance(background) + 0.05;

    // Ensure larger luminance is in numerator
    double ratio = lum1 > lum2 ? lum1 / lum2 : lum2 / lum1;
    return ratio;
  }

  // ============================================================================
  // WCAG COMPLIANCE CHECKS
  // ============================================================================

  /// Check if contrast meets WCAG AA standard for normal text (4.5:1)
  ///
  /// Normal text is defined as text smaller than 18pt (24px) or
  /// smaller than 14pt (18.67px) if bold.
  static bool meetsWcagAA(Color foreground, Color background) {
    return contrastRatio(foreground, background) >= wcagAANormalText;
  }

  /// Check if contrast meets WCAG AA standard for large text (3:1)
  ///
  /// Large text is defined as 18pt (24px) or larger, or
  /// 14pt (18.67px) or larger if bold.
  static bool meetsWcagAALarge(Color foreground, Color background) {
    return contrastRatio(foreground, background) >= wcagAALargeText;
  }

  /// Check if contrast meets WCAG AAA standard for normal text (7:1)
  ///
  /// WCAG AAA is the highest level of accessibility conformance.
  static bool meetsWcagAAA(Color foreground, Color background) {
    return contrastRatio(foreground, background) >= wcagAAANormalText;
  }

  /// Check if contrast meets WCAG AAA standard for large text (4.5:1)
  static bool meetsWcagAAALarge(Color foreground, Color background) {
    return contrastRatio(foreground, background) >= wcagAAALargeText;
  }

  /// Check if contrast meets requirements for UI components (3:1)
  ///
  /// UI components include: buttons, form inputs, focus indicators,
  /// icons, and other interactive elements.
  static bool meetsUIComponentRequirement(Color foreground, Color background) {
    return contrastRatio(foreground, background) >= wcagUIComponents;
  }

  // ============================================================================
  // REPORTING AND DEBUGGING
  // ============================================================================

  /// Get formatted contrast ratio string with pass/fail indicators
  ///
  /// Returns a human-readable string like:
  /// "4.50:1 [AA Pass] [AAA Fail]"
  ///
  /// Example:
  /// \`\`\`dart
  /// final report = WCAGContrast.getContrastReport(Colors.white, primaryColor);
  /// print(report);
  /// \`\`\`
  static String getContrastReport(Color foreground, Color background) {
    double ratio = contrastRatio(foreground, background);
    bool passAA = ratio >= wcagAANormalText;
    bool passAAA = ratio >= wcagAAANormalText;

    final aaStatus = passAA ? '[AA Pass]' : '[AA Fail]';
    final aaaStatus = passAAA ? '[AAA Pass]' : '[AAA Fail]';

    return '\${ratio.toStringAsFixed(2)}:1 \$aaStatus \$aaaStatus';
  }

  /// Get detailed accessibility report for a color pair
  ///
  /// Returns a map with all WCAG level results:
  /// \`\`\`dart
  /// {
  ///   'ratio': 4.5,
  ///   'aa_normal': true,
  ///   'aa_large': true,
  ///   'aaa_normal': false,
  ///   'aaa_large': true,
  ///   'ui_components': true,
  /// }
  /// \`\`\`
  static Map<String, dynamic> getDetailedReport(Color foreground, Color background) {
    final ratio = contrastRatio(foreground, background);
    return {
      'ratio': ratio,
      'aa_normal': ratio >= wcagAANormalText,
      'aa_large': ratio >= wcagAALargeText,
      'aaa_normal': ratio >= wcagAAANormalText,
      'aaa_large': ratio >= wcagAAALargeText,
      'ui_components': ratio >= wcagUIComponents,
    };
  }

  /// Suggest a lighter or darker color to meet WCAG AA
  ///
  /// Returns a color that meets the minimum contrast ratio when
  /// paired with the background color.
  ///
  /// [foreground] - The color to adjust
  /// [background] - The background color to compare against
  /// [targetRatio] - The target contrast ratio (default: 4.5 for AA)
  static Color? suggestAccessibleColor(
    Color foreground,
    Color background, {
    double targetRatio = wcagAANormalText,
  }) {
    final currentRatio = contrastRatio(foreground, background);
    if (currentRatio >= targetRatio) {
      return foreground; // Already accessible
    }

    final backgroundLum = _relativeLuminance(background);

    // Try both lighter and darker versions
    Color? lighter = _adjustBrightness(foreground, 1.2, targetRatio, background);
    Color? darker = _adjustBrightness(foreground, 0.8, targetRatio, background);

    // Return the one closer to original if both work
    if (lighter != null && darker != null) {
      final lighterDiff = (lighter.computeLuminance() - foreground.computeLuminance()).abs();
      final darkerDiff = (darker.computeLuminance() - foreground.computeLuminance()).abs();
      return lighterDiff < darkerDiff ? lighter : darker;
    }

    return lighter ?? darker;
  }

  /// Internal helper to adjust brightness iteratively
  static Color? _adjustBrightness(
    Color color,
    double factor,
    double targetRatio,
    Color background,
  ) {
    Color adjusted = color;
    for (int i = 0; i < 20; i++) {
      final hsv = HSVColor.fromColor(adjusted);
      final newValue = (hsv.value * factor).clamp(0.0, 1.0);
      adjusted = hsv.withValue(newValue).toColor();

      if (contrastRatio(adjusted, background) >= targetRatio) {
        return adjusted;
      }
    }
    return null;
  }

  {{#if includeVerification}}
  // ============================================================================
  // THEME VERIFICATION (Debug Only)
  // ============================================================================

  /// Verify app theme colors meet WCAG standards
  ///
  /// Call this in debug mode to ensure your theme colors are accessible.
  /// Prints a detailed report to the console.
  ///
  /// Example:
  /// \`\`\`dart
  /// // In main.dart or a test file
  /// WCAGContrast.verifyThemeContrast();
  /// \`\`\`
  static void verifyThemeContrast() {
    debugPrint('\\n===============================================');
    debugPrint('  WCAG Contrast Verification Report');
    debugPrint('===============================================\\n');

    // Define color pairs to test
    final testPairs = <String, List<Color>>{
      {{#each verificationPairs}}
      '{{name}}': [{{foreground}}, {{background}}],
      {{/each}}
    };

    testPairs.forEach((name, colors) {
      final report = getContrastReport(colors[0], colors[1]);
      debugPrint('  \$name: \$report');
    });

    debugPrint('\\n===============================================\\n');
  }
  {{/if}}
}

// ============================================================================
// EXTENSION FOR EASY COLOR ACCESSIBILITY CHECKS
// ============================================================================

/// Extension on Color for convenient accessibility checks
extension WCAGColorExtension on Color {
  /// Check if this color meets WCAG AA against a background
  bool meetsWcagAA(Color background) {
    return WCAGContrast.meetsWcagAA(this, background);
  }

  /// Check if this color meets WCAG AAA against a background
  bool meetsWcagAAA(Color background) {
    return WCAGContrast.meetsWcagAAA(this, background);
  }

  /// Get contrast ratio against a background color
  double contrastWith(Color background) {
    return WCAGContrast.contrastRatio(this, background);
  }

  /// Get accessibility report against a background color
  String accessibilityReport(Color background) {
    return WCAGContrast.getContrastReport(this, background);
  }
}
`;

// ============================================================================
// DEFAULT VALUES FOR HANDLEBARS CONTEXT
// ============================================================================

export interface WCAGContrastConfig {
  includeVerification: boolean;
  verificationPairs?: Array<{
    name: string;
    foreground: string;
    background: string;
  }>;
}

export const DEFAULT_WCAG_CONTRAST_CONFIG: WCAGContrastConfig = {
  includeVerification: true,
  verificationPairs: [
    {
      name: "White on Primary",
      foreground: "Colors.white",
      background: "const Color(0xFF6366F1)",
    },
    {
      name: "White on Accent",
      foreground: "Colors.white",
      background: "const Color(0xFF8B5CF6)",
    },
    {
      name: "Dark on Light",
      foreground: "Colors.black87",
      background: "Colors.white",
    },
    {
      name: "Gold on Dark",
      foreground: "const Color(0xFFD4AF37)",
      background: "const Color(0xFF1E293B)",
    },
  ],
};

// ============================================================================
// TYPESCRIPT WCAG FUNCTIONS (for tool validation)
// ============================================================================

/**
 * Calculate relative luminance for a hex color
 * Implements WCAG 2.1 formula with sRGB gamma correction
 */
export function relativeLuminance(hex: string): number {
  const rgb = hexToRgb(hex);
  if (!rgb) return 0;

  let r = rgb.r / 255;
  let g = rgb.g / 255;
  let b = rgb.b / 255;

  r = r <= 0.03928 ? r / 12.92 : Math.pow((r + 0.055) / 1.055, 2.4);
  g = g <= 0.03928 ? g / 12.92 : Math.pow((g + 0.055) / 1.055, 2.4);
  b = b <= 0.03928 ? b / 12.92 : Math.pow((b + 0.055) / 1.055, 2.4);

  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/**
 * Calculate contrast ratio between two hex colors
 */
export function wcagContrastRatio(foreground: string, background: string): number {
  const lum1 = relativeLuminance(foreground) + 0.05;
  const lum2 = relativeLuminance(background) + 0.05;
  return lum1 > lum2 ? lum1 / lum2 : lum2 / lum1;
}

/**
 * Check if colors meet WCAG AA for normal text (4.5:1)
 */
export function meetsWcagAA(foreground: string, background: string): boolean {
  return wcagContrastRatio(foreground, background) >= 4.5;
}

/**
 * Check if colors meet WCAG AA for large text (3:1)
 */
export function meetsWcagAALarge(foreground: string, background: string): boolean {
  return wcagContrastRatio(foreground, background) >= 3.0;
}

/**
 * Check if colors meet WCAG AAA for normal text (7:1)
 */
export function meetsWcagAAA(foreground: string, background: string): boolean {
  return wcagContrastRatio(foreground, background) >= 7.0;
}

/**
 * Get formatted contrast report
 */
export function getWcagContrastReport(foreground: string, background: string): string {
  const ratio = wcagContrastRatio(foreground, background);
  const passAA = ratio >= 4.5;
  const passAAA = ratio >= 7.0;

  const aaStatus = passAA ? "[AA Pass]" : "[AA Fail]";
  const aaaStatus = passAAA ? "[AAA Pass]" : "[AAA Fail]";

  return `${ratio.toFixed(2)}:1 ${aaStatus} ${aaaStatus}`;
}

/**
 * Get detailed accessibility report
 */
export function getDetailedWcagReport(foreground: string, background: string): {
  ratio: number;
  aa_normal: boolean;
  aa_large: boolean;
  aaa_normal: boolean;
  aaa_large: boolean;
  ui_components: boolean;
} {
  const ratio = wcagContrastRatio(foreground, background);
  return {
    ratio,
    aa_normal: ratio >= 4.5,
    aa_large: ratio >= 3.0,
    aaa_normal: ratio >= 7.0,
    aaa_large: ratio >= 4.5,
    ui_components: ratio >= 3.0,
  };
}

/**
 * Helper: Convert hex to RGB
 */
function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : null;
}

// ============================================================================
// TEMPLATE DEFINITION
// ============================================================================

export const WCAG_CONTRAST_TEMPLATE: Template = {
  id: "design-wcag-contrast",
  name: "WCAG Contrast Calculator",
  description: "WCAG 2.1 compliant contrast ratio calculator with AA/AAA checking",
  type: "file",
  source: WCAG_CONTRAST_SOURCE,
  output: {
    path: "lib/theme",
    filename: "wcag_contrast",
    extension: "dart",
  },
};

export default WCAG_CONTRAST_TEMPLATE;
